#手續費
TakerFee         = 0.0000
# 10%
RangePremium     = 0.1
# 10US
LeastTotalValue = 10
# Rate Second
DelayTime       = 5

ExchangeName = "FTXOTC"
[FTX]
SubAccount = "Saber"

#區間內放交易對
[CoinStrip]
key1            = EOS,USDT
key2            = EOS,BTC,USDT

#預定多組交易對
[CoinStrip2]
key1            = FTT,USDT
key2            = FTT,BTC,USDT


# 利潤, 加速, 價值(美元計價)
[RankS]
MinProfit     = 0.003
PlusSecond    = -3
TotalValuesUS = 100

[RankN]
MinProfit     = 0.001
PlusSecond    = -2
TotalValuesUS = 100


