#手續費
TakerFee         = 0.000168
# 10%
RangePremium     = 0.1
# 10US
LeastTotalValue = 10
# Rate Second
DelayTime       = 3

ExchangeName = "FTX"
[FTX]
SubAccount = "apicaller"

#區間內放交易對
[CoinStrip]
key1            = FTT,USD
key2            = FTT,BTC,USD

#預定多組交易對
[CoinStrip2]
key1            = FTT,USDT
key2            = FTT,BTC,USDT


# 利潤, 加速, 價值(美元計價)
[RankS]
MinProfit     = 0.003
PlusSecond    = -1
TotalValuesUS = 1193

[RankN]
MinProfit     = 0.001
PlusSecond    = -1
TotalValuesUS = 1190


