#溢價10%買入 =0.1
RangePremium     = 0.1
# 10 最後一個幣值
LeastTotalValue = 10
# Rate MilliSecond
DelayTime       = 50
# 多久顯示一次還活著
ShowLiveSecond = 60

ExchangeName = "FTX"
[FTX]
SubAccount = "tester"

#區間內放交易對
#key 開頭就會被設定成交易對
[CoinStrip1]
key1            = FTT,USD
key2            = FTT,BTC,USD
key3            = FTT,USDT,USD
# 利潤, 加速, 價值(美元計價)
MinProfit     = 0.0007
PlusMilliSecond    = -1
TotalValuesUS = 2500


#多組交易對
[CoinStrip2]
key1            = BTC,USD
key2            = BTC,USDT,USD
MinProfit     = 0.0007
PlusMilliSecond    = -1
TotalValuesUS = 2500

#多組交易對
[CoinStrip3]
key1            = ETH,USD
key2            = ETH,USDT,USD
MinProfit     = 0.0007
PlusMilliSecond    = -1
TotalValuesUS = 1000

