[CrossExchange]
DelayMilliSecond= 500
OverPrice=        0.03
MinSellProfit=    -0.001
MinSumProfit=     0.0050
MaxHoldVolume=    20000.0
MaxHoldeExchangePercent = 0.20 #100% = 1
MaxHoldBuffer=      0.01
MinCreateProfit=  0.0060
MinVolume =        5
StopLosePercent = -0.10
EnableDBLog=false


[Exchanger]
Exchanges= "Binancef,FTX"

[Futures]
SymbolNames ="ADA-USDT-0,BCH-USDT-0,BNB-USDT-0,BTC-USDT-0,COMP-USDT-0,DOGE-USDT-0,EOS-USDT-0,ETC-USDT-0,ETH-USDT-0,KNC-USDT-0,LINK-USDT-0,LTC-USDT-0,THETA-USDT-0,TRX-USDT-0,VET-USDT-0,XRP-USDT-0,XTZ-USDT-0"
#ALGO-USDT-0,

[COMP-USDT-0]
MinSellProfit=    -0.0013
MinSumProfit=     0.0070
MinCreateProfit=  0.0080

[FTX]
SubAccount = "tester-exchanger"

[Binancef]
Key=***REMOVED***
SecretKey=***REMOVED***