[CrossExchange]
DelayMilliSecond= 100
DealtMilliSecond= 200
OverPrice=        0.03
MinSellProfit=    -0.0010
MinSumProfit=     0.0050
MaxHoldVolume=    20000.0
MaxHoldeExchangePercent = 0.20 #100% = 1
MaxHoldBuffer=      0.01
MinCreateProfit=  0.0060
MinVolume =        5
StopLosePercent = -0.10
EnableDBLog=false
ShowLiveSecond= 60
IsShowProfitLog=true


[Exchanger]
Exchanges= "Binancef,Bybilinear"

[Futures]
#SymbolNames ="ADA-USDT-0,BCH-USDT-0,BNB-USDT-0,BTC-USDT-0,COMP-USDT-0,DOGE-USDT-0,EOS-USDT-0,ETC-USDT-0,ETH-USDT-0,KNC-USDT-0,LINK-USDT-0,LTC-USDT-0,THETA-USDT-0,TRX-USDT-0,VET-USDT-0,XRP-USDT-0,XTZ-USDT-0"
SymbolNames ="BTC-USDT-0,ETH-USDT-0,SOL-USDT-0,APT-USDT-0,OP-USDT-0,DOGE-USDT-0,MATIC-USDT-0,FTM-USDT-0,GALA-USDT-0,DYDX-USDT-0,XRP-USDT-0,ATOM-USDT-0,AVAX-USDT-0,LTC-USDT-0,ADA-USDT-0,NEAR-USDT-0,AXS-USDT-0,MASK-USDT-0,GMT-USDT-0,INJ-USDT-0,MAGIC-USDT-0,MANA-USDT-0,APE-USDT-0,ETC-USDT-0,LDO-USDT-0,SAND-USDT-0,BNB-USDT-0,SHIB1000-USDT-0,LINK-USDT-0,SFP-USDT-0,BIT-USDT-0,RNDR-USDT-0,FIL-USDT-0,INJ-USDT-0,CRV-USDT-0,AR-USDT-0,DOT-USDT-0,HOOK-USDT-0,STG-USDT-0,XTZ-USDT-0"
#ALGO-USDT-0,

[COMP-USDT-0]
MinSellProfit=    -0.0013
MinSumProfit=     0.0070
MinCreateProfit=  0.0080

[APT-USDT-0]
MinSellProfit=    -0.0013
MinSumProfit=     0.0070
MinCreateProfit=  0.0080


[Binancef]
Key=***REMOVED***
SecretKey=***REMOVED***